apiVersion: jaegertracing.io/v1
kind: "Jaeger"
metadata:
  name: jaeger
  namespace: observability
spec:
  strategy: allInOne
  ingress:
    enabled: false
  allInOne:
    image: jaegertracing/all-in-one
    options:
      query:
        base-path: /jaeger
