apiVersion: jaegertracing.io/v1
kind: "Jaeger"
metadata:
  name: jaeger
  namespace: default
spec:
  strategy: allInOne
  ingress:
    enabled: false
  allInOne:
    image: jaegertracing/all-in-one:1.22
    options:
      query:
        base-path: /jaeger
