apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-subscriber
  namespace: default
  labels:
    app: node-subscriber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-subscriber
  template:
    metadata:
      labels:
        app: node-subscriber
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "node-subscriber"
        dapr.io/app-port: "3000"
        dapr.io/log-level: debug
        dapr.io/config: "tracing"
    spec:
      containers:
      - name: node-subscriber
        image: ghcr.io/dapr/samples/pubsub-node-subscriber:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Always